export const carsConstant = {
    GET_CARS_REQUEST: 'GET_CARS_REQUEST',
    GET_CARS_REQUEST_SUCCESS: 'GET_CARS_REQUEST_SUCCESS',
    GET_CARS_REQUEST_FAILURE: 'GET_CARS_REQUEST_FAILURE',

    SEARCH_USER: 'SEARCH_USER',
};
